services:
  - type: web
    name: hotel-management-website
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: project.settings
    staticPublishPath: staticfiles
